type ChatId = {
    server: string;
    user: string;
    _serialized: string;
};

type OriginalSelfAuthor = {
    server: string;
    user: string;
    _serialized: string;
};

type Sender = {
    id: ChatId;
    name: string;
    shortName: string;
    pushname: string;
    type: string;
    isBusiness: boolean;
    isEnterprise: boolean;
    isSmb: boolean;
    isContactSyncCompleted: number;
    textStatusLastUpdateTime: number;
    syncToAddressbook: boolean;
    formattedName: string;
    isMe: boolean;
    isMyContact: boolean;
    isPSA: boolean;
    isUser: boolean;
    isWAContact: boolean;
    profilePicThumbObj: any;
    msgs: any;
};

type MediaData = {
    type: string;
    mediaStage: string;
    size: number;
    filehash: string;
    mimetype: string;
    mediaBlob: any;
    fullHeight: number;
    fullWidth: number;
    aspectRatio: number;
    animationDuration: number;
    animatedAsNewMsg: boolean;
    isViewOnce: boolean;
    staticUrl: string;
    _swStreamingSupported: boolean;
    _listeningToSwSupport: boolean;
    isVcardOverMmsDocument: boolean;
};

export type Message = {
    id: string;
    rowId: number;
    viewed: boolean;
    body: string;
    type: string;
    t: number;
    from: string;
    to: string;
    ack: number;
    invis: boolean;
    star: boolean;
    kicNotified: boolean;
    interactiveAnnotations: any[];
    deprecatedMms3Url: string;
    directPath: string;
    mimetype: string;
    filehash: string;
    encFilehash: string;
    size: number;
    mediaKey: string;
    mediaKeyTimestamp: number;
    isViewOnce: boolean;
    width: number;
    height: number;
    staticUrl: string;
    scanLengths: any[];
    isFromTemplate: boolean;
    pollOptions: any[];
    pollInvalidated: boolean;
    latestEditMsgKey: any;
    latestEditSenderTimestampMs: any;
    mentionedJidList: any[];
    groupMentions: any[];
    eventInvalidated: boolean;
    isVcardOverMmsDocument: boolean;
    isForwarded: boolean;
    hasReaction: boolean;
    originalSelfAuthor: OriginalSelfAuthor;
    productHeaderImageRejected: boolean;
    lastPlaybackProgress: number;
    isDynamicReplyButtonsMsg: boolean;
    isCarouselCard: boolean;
    parentMsgId: any;
    isMdHistoryMsg: boolean;
    stickerSentTs: number;
    isAvatar: boolean;
    lastUpdateFromServerTs: number;
    invokedBotWid: any;
    botTargetSenderJid: any;
    bizBotType: any;
    botResponseTargetId: any;
    botPluginType: any;
    botPluginReferenceIndex: any;
    botPluginSearchProvider: any;
    botPluginSearchUrl: any;
    botPluginSearchQuery: any;
    botPluginMaybeParent: boolean;
    botReelPluginThumbnailCdnUrl: any;
    botMsgBodyType: any;
    requiresDirectConnection: boolean;
    bizContentPlaceholderType: any;
    hostedBizEncStateMismatch: boolean;
    senderOrRecipientAccountTypeHosted: boolean;
    placeholderCreatedWhenAccountIsHosted: boolean;
    chatId: ChatId;
    fromMe: boolean;
    sender: Sender;
    timestamp: number;
    content: string;
    isGroupMsg: boolean;
    mediaData: MediaData;
};
